### PR TITLE
Add "COD" to _rcsb_chem_comp_related.resource_name enumerations and update mmcif_pdbx_v5_next.dic to version 5.387

### PR DESCRIPTION
**Pull request by piehld**
- Add "COD" to _rcsb_chem_comp_related.resource_name enumerations (Jira ticket: [RO-4051](https://rcsbpdb.atlassian.net/browse/RO-4051))
- Update `mmcif_pdbx_v5_next.dic` to version 5.387
- Add new Pfam mapping file, `pdbmap.gz`, to replace `pdb_pfamA_reg.txt.gz` which is no longer updated/supported (Jira ticket: [RO-4067](https://rcsbpdb.atlassian.net/browse/RO-4067))

### CODE REVIEW

**Comment by piehld** [comment]
Thanks @brindakv! Just tested this with https://github.com/rcsb/py-rcsb_db/pull/65, and it works great. Feel free to merge both. 

Also, do you want to copy files to `rcsb-json-schema` too, or do you want me to?

**Comment by brindakv** [comment]
> Thanks @brindakv! Just tested this with [rcsb/py-rcsb_db#65](https://github.com/rcsb/py-rcsb_db/pull/65), and it works great. Feel free to merge both.
> 
> Also, do you want to copy files to `rcsb-json-schema` too, or do you want me to?

Thanks @piehld. I had already created a branch on rcsb-json-schema. I created a PR on that repo and requested @valasatava to review.

**Comment by piehld** [comment]
Thanks! Once that is approved then we could merge both that one and this PR.

**Comment by piehld** [comment]
Also I'll need to merge this `py-rcsb_utils_dictionary` one at the same time: https://github.com/rcsb/py-rcsb_utils_dictionary/pull/66

**Pull request merged**
