### PR TITLE
Feat: Update search contexts: RO-2919 add rcsb_chem_comp_synonyms.name to list of ATTRIBUTE_NAMES for 'suggest' SEARCH_TYPE

### PR DESCRIPTION
**Pull request by piehld**

### CODE REVIEW

**Comment by valasatava** [comment]
@piehld one question: seems that changes to the dictionaries should be also committed. Aren't they sources for those changes?

**Comment by piehld** [comment]
@valasatava This feature did not require any changes to the dictionaries, only to the schemas. Li and I tested these new schema files on a development instance, and everything looked good.

**Comment by piehld** [comment]
@valasatava The two related commits that needed to be made in py-rcsb_exdb_assets are:
https://github.com/rcsb/py-rcsb_exdb_assets/commit/b91a625d08e712e2584e0fb087c2cd79c7699f2a
and
https://github.com/rcsb/py-rcsb_exdb_assets/commit/6b105784abf4bc6f3fb5ca138a2ee54b4e11960f

**Comment by valasatava** [comment]
> @valasatava The two related commits that needed to be made in py-rcsb_exdb_assets are: [b91a625](https://github.com/rcsb/py-rcsb_exdb_assets/commit/b91a625d08e712e2584e0fb087c2cd79c7699f2a) and [6b10578](https://github.com/rcsb/py-rcsb_exdb_assets/commit/6b105784abf4bc6f3fb5ca138a2ee54b4e11960f)

Great! Somehow I missed this. Thanks!

**Comment by josemduarte** [comment]
Great, thanks @piehld ! 

It seems that commit b91a625 was already in master so it didn't show up in the diff here. I was confused by that too. 

We will now need to have an equivalent pull request to rcsb-json-schema repo. Let's talk about that in the meeting.

**Comment by piehld** [comment]
@josemduarte I created a PR in the rcsb-json-schema repo earlier today.

**Comment by josemduarte** [comment]
Oh sorry missed that one! I'll take a look

**Pull request merged**
