### PR TITLE
Schema updates from PDBx/mmCIF and ModelCIF

### PR DESCRIPTION
**Pull request by brindakv**
@piehld This PR updates RCSB schemas to match PDBx/mmCIF v5.373 and ModelCIF v1.4.4. I tested the updated schemas on a selected subset of PDB structures and CSMs and there are no issues. However, since this is a large scale change, it needs to be tested further before merging. 

Please note that https://github.com/rcsb/py-rcsb_exdb_assets/blob/dev-schema-updates-bv/dictionary_files/reference/mmcif_ma.dic is now replaced by https://github.com/rcsb/py-rcsb_exdb_assets/blob/dev-schema-updates-bv/dictionary_files/reference/mmcif_ma_ext.dic to accommodate changes in the way [ModelCIF dictionary](https://github.com/ihmwg/ModelCIF) is distributed. Accordingly the [ExDB config example yml file](https://github.com/rcsb/py-rcsb_db/blob/dev-schema-updates-bv/rcsb/db/config/exdb-config-example.yml) has been updated [here](https://github.com/rcsb/py-rcsb_db/blob/dev-schema-updates-bv/rcsb/db/config/exdb-config-example.yml#L131) and [here](https://github.com/rcsb/py-rcsb_db/blob/dev-schema-updates-bv/rcsb/db/config/exdb-config-example.yml#L284).

### CODE REVIEW

**Comment by brindakv** [comment]
@piehld There is an issue with `_chem_comp.three_letter_code` that needs to be addressed. Please do not test the updated schema yet.

**Comment by piehld** [comment]
No problem @brindakv, thanks for the heads up and catching that! Just let me know when it's ready.

**Comment by brindakv** [comment]
@piehld Schema updates are ready for testing.

**Review by piehld — APPROVED** [review]
LGTM, thanks @brindakv! Tested and works for both CSMs and Experimental structures.

**Pull request merged**
