### PR TITLE
RO-4169: Change pdbx_src_id to be type integer

### PR DESCRIPTION
**Pull request by piehld**
RO-4169: Change rcsb_entity_source_organism.pdbx_src_id and rcsb_entity_host_organism.pdbx_src_id to be type integer

### CODE REVIEW

**Comment by josemduarte** [comment]
Thanks @piehld . Question: does this need to be pushed to rcsb-json-schema too?

**Comment by piehld** [comment]
@josemduarte Yes it will be, but I'd like @brindakv to review this here first before creating a separate PR for rcsb-json-schema.

**Comment by ChunxiaoB** [comment]
> @josemduarte Yes it will be, but I'd like @brindakv to review this here first before creating a separate PR for rcsb-json-schema.

FYI - 

Some minor rcsb-redwood code adjustments are required after we change the schema, such as https://github.com/rcsb/rcsb-redwood/blob/7f04d159ca8b240def3ac05faba4f0ab0f6922ba/src/main/java/org/rcsb/redwood/util/TaxonomyUtils.java#L49

**Comment by piehld** [comment]
@ChunxiaoB Oh good to know, thank you for the heads up! We will definitely be sure to let you know before we merge anything.

**Review by brindakv — APPROVED** [review]
Thanks @piehld. Looks good to me. 

Hope the data doesn't have any exceptions.

**Pull request merged**
